/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoRede;

import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import javax.swing.JOptionPane;
import sourceGui.ControloGui;
import sourceGuiControlo.ImagemFundoModelo;

/**
 *
 * @author Again
 */
public class PanelDadosChat extends javax.swing.JPanel {
    
    public PrintWriter escritor;
    public Socket socket;
    public String nome;
    public String ip;
    public Scanner leitor;
    public String nomeJg1;
    public String nomeJg2;
    public String numBatalha;
    public String numJogos;
    
    public String bigArgumento="";
//    public Jogo jogo;
    /**
     * Creates new form PanelDadosChat
     */
    public PanelDadosChat(String nome,String ip, String nomeJg1, String nomeJg2, String numBatalhas, String numJogos) {
 
        this.ip=ip;
        this.nomeJg1 = nomeJg1;
        this.nomeJg2 = nomeJg2;
        this.numBatalha = numBatalhas;
        this.numJogos = numJogos;
        
        initComponents();
        jtp1.setText(nomeJg1);
        jtp2.setText(nomeJg2);
        jTextField4.setText(numJogos);
        jtfBatalha.setText(numBatalhas);
        configuararrede();
        this.nome = nome;
    }
    
    public PanelDadosChat(String nome,String ip, int i) {
 
        this.ip=ip;
        
        initComponents();
        jtp1.setText("Aires Velozo");
        jtp2.setText("Manuel Meneses");
        jTextField4.setText("0");
        jtfBatalha.setText("13");
        configuararrede();
        this.nome = nome;
    }

    public void setNomeJg2(String nomeJg2) {
        this.nomeJg2 = nomeJg2;
        jtp2.setText(nomeJg2);
    }

    public void setNomeJg1(String nomeJg1) {
        this.nomeJg1 = nomeJg1;
        jtp1.setText(nomeJg1);
    }

    public void setNumBatalha(String numBatalha) {
        this.numBatalha = numBatalha;
        jtfBatalha.setText(numBatalha);
    }
    
    public void actualizaTextFields()
    {
        
    }

  public void configuararrede(){
        try{
            // 127.0.0.1
            socket = new Socket(ip, 5001);
            System.out.println("Conectado..."); 
            escritor = new PrintWriter(socket.getOutputStream());
            JOptionPane.showMessageDialog(null,"Bug...");
            
            leitor = new Scanner(socket.getInputStream() );
            
           new Thread(new EscutaServidor()).start();
        }catch(Exception ex){}
        
    }
  
    private class EscutaServidor implements Runnable{
        @Override
        public void run(){
            try{
                String texto;
                while((texto = leitor.nextLine()) != null ){
                    jtaHistorico.append(texto+"\n");
                }
            }
            catch(Exception ex){}
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new ImagemFundoModelo(ControloGui.config.imgTheme[ControloGui.config.pos][2]);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtp1 = new javax.swing.JTextField();
        jtp2 = new javax.swing.JTextField();
        jtfBatalha = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new ImagemFundoModelo(ControloGui.config.imgTheme[ControloGui.config.pos][2]);
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaHistorico = new javax.swing.JTextArea();
        jtfTextoEnviar = new javax.swing.JTextField();
        jbtEnviar = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Numero Jogos: ");

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Player1: ");

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Player2: ");

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Numero Batalha");

        jtp1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jtp2.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jtfBatalha.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        jTextField4.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfBatalha, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtp1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jtp2))))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfBatalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chat"));

        jtaHistorico.setColumns(20);
        jtaHistorico.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jtaHistorico.setRows(5);
        jScrollPane1.setViewportView(jtaHistorico);

        jtfTextoEnviar.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jtfTextoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTextoEnviarActionPerformed(evt);
            }
        });

        jbtEnviar.setText("Enviar");
        jbtEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfTextoEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtEnviar))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTextoEnviar)
                    .addComponent(jbtEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEnviarActionPerformed
        // TODO add your handling code here:
        escritor.println(nome+": "+jtfTextoEnviar.getText() );
        escritor.flush();
        jtfTextoEnviar.setText("");
        jtfTextoEnviar.requestFocus();
    }//GEN-LAST:event_jbtEnviarActionPerformed

    private void jtfTextoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTextoEnviarActionPerformed
        // TODO add your handling code here:
        escritor.println(nome+": "+jtfTextoEnviar.getText() );
        escritor.flush();
        jtfTextoEnviar.setText("");
        jtfTextoEnviar.requestFocus();
    }//GEN-LAST:event_jtfTextoEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    public javax.swing.JButton jbtEnviar;
    public static javax.swing.JTextArea jtaHistorico;
    private javax.swing.JTextField jtfBatalha;
    public javax.swing.JTextField jtfTextoEnviar;
    private javax.swing.JTextField jtp1;
    private javax.swing.JTextField jtp2;
    // End of variables declaration//GEN-END:variables
}
