/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rede;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import javax.swing.JOptionPane;
import static rede.Servidor.jogo;
import sourceModelo.Jogo;

/**
 *
 * @author Again
 */
public class ChatCliente extends javax.swing.JFrame {
    
    public PrintWriter escritor;
    public Socket socket;
    public String nome;
    public Scanner leitor;
    
    public String bigArgumento="";
    public Jogo jogo;
    
    
    public ChatCliente(String nome) {
        super("Chat: "+nome);
        this.nome = nome;
        
        jogo = new Jogo();
        
        initComponents();
        setLocationRelativeTo(null);
        configuararrede();
    }

    
    public void configuararrede(){
        try{
            socket = new Socket("127.0.0.1",5000);
            System.out.println("Conectado..."); 
            escritor = new PrintWriter(socket.getOutputStream());
            leitor = new Scanner(socket.getInputStream() );
            //===================================================
            try{    
            ObjectInputStream ois = new ObjectInputStream(socket.getInputStream() );
            jogo = (Jogo) ois.readObject();
            // ois.close();
            }catch(Exception ex){
                System.out.println("Deu pau....");
            }
            JOptionPane.showMessageDialog(null,""+jogo.baralho.getCarta()[0].getPicture() );
            
            new Thread(new EscutaServidor()).start();
        }catch(Exception ex){}
        
    }
    
    private class EscutaServidor implements Runnable{
        @Override
        public void run(){
            try{
                String texto;
                while((texto = leitor.nextLine()) != null ){
                    jtaHistorico.append(texto+"\n");
                }
            }
            catch(Exception ex){}
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaHistorico = new javax.swing.JTextArea();
        jtfTextoEnviar = new javax.swing.JTextField();
        jbtEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat");

        jtaHistorico.setColumns(20);
        jtaHistorico.setRows(5);
        jScrollPane1.setViewportView(jtaHistorico);

        jtfTextoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTextoEnviarActionPerformed(evt);
            }
        });

        jbtEnviar.setText("Enviar");
        jbtEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEnviarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jScrollPane1)
                    .add(layout.createSequentialGroup()
                        .add(jtfTextoEnviar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtEnviar)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jtfTextoEnviar)
                    .add(jbtEnviar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEnviarActionPerformed
        // TODO add your handling code here:
        escritor.println(jtfTextoEnviar.getText());
        escritor.flush();
        jtfTextoEnviar.setText("");
        jtfTextoEnviar.requestFocus();
    }//GEN-LAST:event_jbtEnviarActionPerformed

    private void jtfTextoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTextoEnviarActionPerformed
        // TODO add your handling code here:
        escritor.println(nome+ ": "+jtfTextoEnviar.getText());
        escritor.flush();
        jtfTextoEnviar.setText("");
        jtfTextoEnviar.requestFocus();
    }//GEN-LAST:event_jtfTextoEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              new ChatCliente("Lauro").setVisible(true);
              new ChatCliente("Zua").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtEnviar;
    private javax.swing.JTextArea jtaHistorico;
    private javax.swing.JTextField jtfTextoEnviar;
    // End of variables declaration//GEN-END:variables
    }
